apiVersion: v1
kind: Service # Type of kubernetes resource
metadata:
  name: hello-world # Name of the resource
spec:
  ports: # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8 080
    - name: http
      port: 80
  selector:
    app: hello-world # Map any pod with label `app=go-hello-world` to this service
